// Code generated by MockGen. DO NOT EDIT.
// Source: get_mentor_recruitments_app_service.go
//
// Generated by this command:
//
//	mockgen -source=get_mentor_recruitments_app_service.go -destination=../../../support/mock/app/mentorrecruitmentapp/get_mentor_recruitments_app_service_mock.go -package=mentorrecruitmentapp_mock
//

// Package mentorrecruitmentapp_mock is a generated GoMock package.
package mentorrecruitmentapp_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	mentor_recruitmentdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/mentor_recruitmentdm"
)

// MockGetMentorRecruitmentsAppService is a mock of GetMentorRecruitmentsAppService interface.
type MockGetMentorRecruitmentsAppService struct {
	ctrl     *gomock.Controller
	recorder *MockGetMentorRecruitmentsAppServiceMockRecorder
	isgomock struct{}
}

// MockGetMentorRecruitmentsAppServiceMockRecorder is the mock recorder for MockGetMentorRecruitmentsAppService.
type MockGetMentorRecruitmentsAppServiceMockRecorder struct {
	mock *MockGetMentorRecruitmentsAppService
}

// NewMockGetMentorRecruitmentsAppService creates a new mock instance.
func NewMockGetMentorRecruitmentsAppService(ctrl *gomock.Controller) *MockGetMentorRecruitmentsAppService {
	mock := &MockGetMentorRecruitmentsAppService{ctrl: ctrl}
	mock.recorder = &MockGetMentorRecruitmentsAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMentorRecruitmentsAppService) EXPECT() *MockGetMentorRecruitmentsAppServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetMentorRecruitmentsAppService) Exec(ctx context.Context) ([]*mentor_recruitmentdm.MentorRecruitment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx)
	ret0, _ := ret[0].([]*mentor_recruitmentdm.MentorRecruitment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetMentorRecruitmentsAppServiceMockRecorder) Exec(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetMentorRecruitmentsAppService)(nil).Exec), ctx)
}
