// Code generated by MockGen. DO NOT EDIT.
// Source: mentor_recruitment_query_service.go
//
// Generated by this command:
//
//	mockgen -source=mentor_recruitment_query_service.go -destination=../../../support/mock/app/mentorrecruitmentapp/mentor_recruitment_query_service_mock.go -package=mentorrecruitmentapp_mock
//

// Package mentorrecruitmentapp_mock is a generated GoMock package.
package mentorrecruitmentapp_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	mentor_recruitmentdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/mentor_recruitmentdm"
)

// MockMentorRecruitmentQueryService is a mock of MentorRecruitmentQueryService interface.
type MockMentorRecruitmentQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockMentorRecruitmentQueryServiceMockRecorder
	isgomock struct{}
}

// MockMentorRecruitmentQueryServiceMockRecorder is the mock recorder for MockMentorRecruitmentQueryService.
type MockMentorRecruitmentQueryServiceMockRecorder struct {
	mock *MockMentorRecruitmentQueryService
}

// NewMockMentorRecruitmentQueryService creates a new mock instance.
func NewMockMentorRecruitmentQueryService(ctrl *gomock.Controller) *MockMentorRecruitmentQueryService {
	mock := &MockMentorRecruitmentQueryService{ctrl: ctrl}
	mock.recorder = &MockMentorRecruitmentQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMentorRecruitmentQueryService) EXPECT() *MockMentorRecruitmentQueryServiceMockRecorder {
	return m.recorder
}

// GetMentorRecruitments mocks base method.
func (m *MockMentorRecruitmentQueryService) GetMentorRecruitments(ctx context.Context) ([]*mentor_recruitmentdm.MentorRecruitment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentorRecruitments", ctx)
	ret0, _ := ret[0].([]*mentor_recruitmentdm.MentorRecruitment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentorRecruitments indicates an expected call of GetMentorRecruitments.
func (mr *MockMentorRecruitmentQueryServiceMockRecorder) GetMentorRecruitments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentorRecruitments", reflect.TypeOf((*MockMentorRecruitmentQueryService)(nil).GetMentorRecruitments), ctx)
}
