# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
  skip-dirs:
    - vendor
    - tmp
    - .git

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/TakayukiHirano117/architecture-study

issues:
  exclude-rules:
    - path: _mock\.go
      linters:
        - unused
    - path: mock/
      linters:
        - unused
  exclude-generated: true
