@startuml ユーザー集約
skinparam packageStyle rectangle
left to right direction

package ユーザー集約 {
    object ユーザー {
        ID
        名前
        メールアドレス
        パスワード
        List<スキル>
        List<経歴>
        自己紹介
    }

    object スキル {
        ID
        List<タグID>
        評価
        年数
    }

    object 経歴 {
        ID
        詳細
        西暦from
        西暦to
    }

    ユーザー "1" --> "0..*" 経歴
    ユーザー "1" --> "1..*" スキル
}

スキル "1" --> "1" タグ集約.タグ

package プラン集約 {
    object プラン {
        ID
        タイトル
        カテゴリ
        List<タグID>
        内容
        ステータス
        相談形式
        金額
        相談方式
        メンターID
    }

    object ユーザー {

    }
}

プラン "1" --> "0..*" ユーザー

package メンター募集集約 {
    object メンター募集 {
        ID
        タイトル
        カテゴリ
        相談形式
        相談方式
        ディスクリプション
        予算
        応募期間
        ステータス
        List<タグID>
    }
}

ユーザー "1" --> "0..*" メンター募集
メンター募集 "1" --> "0..*" タグ集約.タグ

package メンター募集提案集約 {
    object メンター募集提案 {
        ID
        提案内容
    }

    object ユーザー {

    }

    object メンター募集 {

    }

}
ユーザー "1" --> "0..*" メンター募集提案
メンター募集 "1" --> "0..*" メンター募集提案

package 契約集約 {
    object 契約 {
        ID
        メンティーID(ユーザーID)
        プランID
    }

    object ユーザー {

    }

    object プラン {

    }
}

ユーザー "1" --> "0..*" 契約
プラン "0..*" --> "0..*" 契約

package タグ集約 {
    object タグ {
        ID
        タグ名
    }
    タグ "1" --> "0..*" プラン集約
}

package 契約リクエスト集約 {
    object 契約リクエスト {
        ID
        メッセージ
        リクエスト時のプランの金額
        ユーザーID
        プランID
    }

}
プラン "1" --> "0..*" 契約リクエスト
ユーザー "1" --> "0..*" 契約リクエスト

@enduml
