// Code generated by MockGen. DO NOT EDIT.
// Source: contract_request_repository.go
//
// Generated by this command:
//
//	mockgen -source=contract_request_repository.go -destination=../../../support/mock/domain/contract_requestdm/contract_request_repository_mock.go -package=contract_requestdm_mock
//

// Package contract_requestdm_mock is a generated GoMock package.
package contract_requestdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	contract_requestdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/contract_requestdm"
)

// MockContractRequestRepository is a mock of ContractRequestRepository interface.
type MockContractRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockContractRequestRepositoryMockRecorder is the mock recorder for MockContractRequestRepository.
type MockContractRequestRepositoryMockRecorder struct {
	mock *MockContractRequestRepository
}

// NewMockContractRequestRepository creates a new mock instance.
func NewMockContractRequestRepository(ctrl *gomock.Controller) *MockContractRequestRepository {
	mock := &MockContractRequestRepository{ctrl: ctrl}
	mock.recorder = &MockContractRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractRequestRepository) EXPECT() *MockContractRequestRepositoryMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockContractRequestRepository) Store(ctx context.Context, contractRequest *contract_requestdm.ContractRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, contractRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockContractRequestRepositoryMockRecorder) Store(ctx, contractRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockContractRequestRepository)(nil).Store), ctx, contractRequest)
}
