// Code generated by MockGen. DO NOT EDIT.
// Source: is_exist_by_plan_id_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=is_exist_by_plan_id_domain_service.go -destination=../../../support/mock/domain/plandm/is_exist_by_plan_id_domain_service_mock.go -package=plandm_mock
//

// Package plandm_mock is a generated GoMock package.
package plandm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	shared "github.com/TakayukiHirano117/architecture-study/src/core/domain/shared"
)

// MockIsExistByPlanIDDomainService is a mock of IsExistByPlanIDDomainService interface.
type MockIsExistByPlanIDDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByPlanIDDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByPlanIDDomainServiceMockRecorder is the mock recorder for MockIsExistByPlanIDDomainService.
type MockIsExistByPlanIDDomainServiceMockRecorder struct {
	mock *MockIsExistByPlanIDDomainService
}

// NewMockIsExistByPlanIDDomainService creates a new mock instance.
func NewMockIsExistByPlanIDDomainService(ctrl *gomock.Controller) *MockIsExistByPlanIDDomainService {
	mock := &MockIsExistByPlanIDDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByPlanIDDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByPlanIDDomainService) EXPECT() *MockIsExistByPlanIDDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByPlanIDDomainService) Exec(ctx context.Context, planID shared.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, planID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByPlanIDDomainServiceMockRecorder) Exec(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByPlanIDDomainService)(nil).Exec), ctx, planID)
}
