// Code generated by MockGen. DO NOT EDIT.
// Source: plan_repository.go
//
// Generated by this command:
//
//	mockgen -source=plan_repository.go -destination=../../../support/mock/domain/plandm/plan_repository_mock.go -package=plandm_mock
//

// Package plandm_mock is a generated GoMock package.
package plandm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	plandm "github.com/TakayukiHirano117/architecture-study/src/core/domain/plandm"
)

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockPlanRepository) Store(ctx context.Context, plan *plandm.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockPlanRepositoryMockRecorder) Store(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPlanRepository)(nil).Store), ctx, plan)
}
