// Code generated by MockGen. DO NOT EDIT.
// Source: build_tags_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=build_tags_domain_service.go -destination=../../../support/mock/domain/tagdm/build_tags_domain_service_mock.go -package=tagdm_mock
//

// Package tagdm_mock is a generated GoMock package.
package tagdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	tagdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/tagdm"
)

// MockBuildTagsDomainService is a mock of BuildTagsDomainService interface.
type MockBuildTagsDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockBuildTagsDomainServiceMockRecorder
	isgomock struct{}
}

// MockBuildTagsDomainServiceMockRecorder is the mock recorder for MockBuildTagsDomainService.
type MockBuildTagsDomainServiceMockRecorder struct {
	mock *MockBuildTagsDomainService
}

// NewMockBuildTagsDomainService creates a new mock instance.
func NewMockBuildTagsDomainService(ctrl *gomock.Controller) *MockBuildTagsDomainService {
	mock := &MockBuildTagsDomainService{ctrl: ctrl}
	mock.recorder = &MockBuildTagsDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildTagsDomainService) EXPECT() *MockBuildTagsDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockBuildTagsDomainService) Exec(ctx context.Context, reqTags []tagdm.TagRequest) ([]tagdm.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, reqTags)
	ret0, _ := ret[0].([]tagdm.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockBuildTagsDomainServiceMockRecorder) Exec(ctx, reqTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockBuildTagsDomainService)(nil).Exec), ctx, reqTags)
}
