// Code generated by MockGen. DO NOT EDIT.
// Source: Is_exist_by_tag_id_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=Is_exist_by_tag_id_domain_service.go -destination=../../../support/mock/domain/tagdm/is_exist_by_tag_id_domain_service_mock.go -package=tagdm_mock
//

// Package tagdm_mock is a generated GoMock package.
package tagdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIsExistByTagIDDomainService is a mock of IsExistByTagIDDomainService interface.
type MockIsExistByTagIDDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByTagIDDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByTagIDDomainServiceMockRecorder is the mock recorder for MockIsExistByTagIDDomainService.
type MockIsExistByTagIDDomainServiceMockRecorder struct {
	mock *MockIsExistByTagIDDomainService
}

// NewMockIsExistByTagIDDomainService creates a new mock instance.
func NewMockIsExistByTagIDDomainService(ctrl *gomock.Controller) *MockIsExistByTagIDDomainService {
	mock := &MockIsExistByTagIDDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByTagIDDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByTagIDDomainService) EXPECT() *MockIsExistByTagIDDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByTagIDDomainService) Exec(ctx context.Context, reqTagID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, reqTagID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByTagIDDomainServiceMockRecorder) Exec(ctx, reqTagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByTagIDDomainService)(nil).Exec), ctx, reqTagID)
}
