// Code generated by MockGen. DO NOT EDIT.
// Source: tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=tag_repository.go -destination=../../../support/mock/domain/tagdm/tag_repository_mock.go -package=tagdm_mock
//

// Package tagdm_mock is a generated GoMock package.
package tagdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	shared "github.com/TakayukiHirano117/architecture-study/src/core/domain/shared"
	tagdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/tagdm"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// BulkInsert mocks base method.
func (m *MockTagRepository) BulkInsert(ctx context.Context, tags []tagdm.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsert", ctx, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsert indicates an expected call of BulkInsert.
func (mr *MockTagRepositoryMockRecorder) BulkInsert(ctx, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsert", reflect.TypeOf((*MockTagRepository)(nil).BulkInsert), ctx, tags)
}

// FindByID mocks base method.
func (m *MockTagRepository) FindByID(ctx context.Context, id shared.UUID) (*tagdm.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*tagdm.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTagRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTagRepository)(nil).FindByID), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockTagRepository) FindByIDs(ctx context.Context, ids []shared.UUID) ([]tagdm.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].([]tagdm.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockTagRepositoryMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockTagRepository)(nil).FindByIDs), ctx, ids)
}

// FindIdByTagName mocks base method.
func (m *MockTagRepository) FindIdByTagName(ctx context.Context, tagName tagdm.TagName) (*shared.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIdByTagName", ctx, tagName)
	ret0, _ := ret[0].(*shared.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIdByTagName indicates an expected call of FindIdByTagName.
func (mr *MockTagRepositoryMockRecorder) FindIdByTagName(ctx, tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIdByTagName", reflect.TypeOf((*MockTagRepository)(nil).FindIdByTagName), ctx, tagName)
}
