// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/domain/tagdm/find_id_by_tag_name_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=src/core/domain/tagdm/find_id_by_tag_name_domain_service.go -destination=src/core/domain/tagdm/find_id_by_tag_name_domain_service_mock.go -package=tagdm
//

// Package tagdm is a generated GoMock package.
package tagdm

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFindIDByTagNameDomainService is a mock of FindIDByTagNameDomainService interface.
type MockFindIDByTagNameDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockFindIDByTagNameDomainServiceMockRecorder
	isgomock struct{}
}

// MockFindIDByTagNameDomainServiceMockRecorder is the mock recorder for MockFindIDByTagNameDomainService.
type MockFindIDByTagNameDomainServiceMockRecorder struct {
	mock *MockFindIDByTagNameDomainService
}

// NewMockFindIDByTagNameDomainService creates a new mock instance.
func NewMockFindIDByTagNameDomainService(ctrl *gomock.Controller) *MockFindIDByTagNameDomainService {
	mock := &MockFindIDByTagNameDomainService{ctrl: ctrl}
	mock.recorder = &MockFindIDByTagNameDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindIDByTagNameDomainService) EXPECT() *MockFindIDByTagNameDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockFindIDByTagNameDomainService) Exec(ctx context.Context, tagName TagName) (*TagID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, tagName)
	ret0, _ := ret[0].(*TagID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockFindIDByTagNameDomainServiceMockRecorder) Exec(ctx, tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockFindIDByTagNameDomainService)(nil).Exec), ctx, tagName)
}
