// Code generated by MockGen. DO NOT EDIT.
// Source: is_exist_by_user_name_exclude_self_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=is_exist_by_user_name_exclude_self_domain_service.go -destination=../../../support/mock/domain/userdm/is_exist_by_user_name_exclude_self_domain_service_mock.go -package=userdm_mock
//

// Package userdm_mock is a generated GoMock package.
package userdm_mock

import (
	context "context"
	reflect "reflect"

	userdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/userdm"
	gomock "go.uber.org/mock/gomock"
)

// MockIsExistByUserNameExcludeSelfDomainService is a mock of IsExistByUserNameExcludeSelfDomainService interface.
type MockIsExistByUserNameExcludeSelfDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder is the mock recorder for MockIsExistByUserNameExcludeSelfDomainService.
type MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder struct {
	mock *MockIsExistByUserNameExcludeSelfDomainService
}

// NewMockIsExistByUserNameExcludeSelfDomainService creates a new mock instance.
func NewMockIsExistByUserNameExcludeSelfDomainService(ctrl *gomock.Controller) *MockIsExistByUserNameExcludeSelfDomainService {
	mock := &MockIsExistByUserNameExcludeSelfDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByUserNameExcludeSelfDomainService) EXPECT() *MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByUserNameExcludeSelfDomainService) Exec(ctx context.Context, userName userdm.UserName, userID userdm.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, userName, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByUserNameExcludeSelfDomainServiceMockRecorder) Exec(ctx, userName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByUserNameExcludeSelfDomainService)(nil).Exec), ctx, userName, userID)
}
