// Code generated by MockGen. DO NOT EDIT.
// Source: is_exist_by_user_id_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=is_exist_by_user_id_domain_service.go -destination=../../../support/mock/domain/userdm/is_exist_by_user_id_domain_service_mock.go -package=userdm_mock
//

// Package userdm_mock is a generated GoMock package.
package userdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	shared "github.com/TakayukiHirano117/architecture-study/src/core/domain/shared"
)

// MockIsExistByUserIDDomainService is a mock of IsExistByUserIDDomainService interface.
type MockIsExistByUserIDDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByUserIDDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByUserIDDomainServiceMockRecorder is the mock recorder for MockIsExistByUserIDDomainService.
type MockIsExistByUserIDDomainServiceMockRecorder struct {
	mock *MockIsExistByUserIDDomainService
}

// NewMockIsExistByUserIDDomainService creates a new mock instance.
func NewMockIsExistByUserIDDomainService(ctrl *gomock.Controller) *MockIsExistByUserIDDomainService {
	mock := &MockIsExistByUserIDDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByUserIDDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByUserIDDomainService) EXPECT() *MockIsExistByUserIDDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByUserIDDomainService) Exec(ctx context.Context, userID shared.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByUserIDDomainServiceMockRecorder) Exec(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByUserIDDomainService)(nil).Exec), ctx, userID)
}
