// Code generated by MockGen. DO NOT EDIT.
// Source: is_exist_by_user_name_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=is_exist_by_user_name_domain_service.go -destination=../../../support/mock/domain/userdm/is_exist_by_user_name_domain_service_mock.go -package=userdm_mock
//

// Package userdm_mock is a generated GoMock package.
package userdm_mock

import (
	context "context"
	reflect "reflect"

	userdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/userdm"
	gomock "go.uber.org/mock/gomock"
)

// MockIsExistByUserNameDomainService is a mock of IsExistByUserNameDomainService interface.
type MockIsExistByUserNameDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByUserNameDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByUserNameDomainServiceMockRecorder is the mock recorder for MockIsExistByUserNameDomainService.
type MockIsExistByUserNameDomainServiceMockRecorder struct {
	mock *MockIsExistByUserNameDomainService
}

// NewMockIsExistByUserNameDomainService creates a new mock instance.
func NewMockIsExistByUserNameDomainService(ctrl *gomock.Controller) *MockIsExistByUserNameDomainService {
	mock := &MockIsExistByUserNameDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByUserNameDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByUserNameDomainService) EXPECT() *MockIsExistByUserNameDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByUserNameDomainService) Exec(ctx context.Context, userName userdm.UserName) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, userName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByUserNameDomainServiceMockRecorder) Exec(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByUserNameDomainService)(nil).Exec), ctx, userName)
}
