// Code generated by MockGen. DO NOT EDIT.
// Source: is_exist_by_category_id_domain_service.go
//
// Generated by this command:
//
//	mockgen -source=is_exist_by_category_id_domain_service.go -destination=../../../support/mock/domain/categorydm/is_exist_by_category_id_domain_service_mock.go -package=categorydm_mock
//

// Package categorydm_mock is a generated GoMock package.
package categorydm_mock

import (
	context "context"
	reflect "reflect"

	categorydm "github.com/TakayukiHirano117/architecture-study/src/core/domain/categorydm"
	gomock "go.uber.org/mock/gomock"
)

// MockIsExistByCategoryIDDomainService is a mock of IsExistByCategoryIDDomainService interface.
type MockIsExistByCategoryIDDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockIsExistByCategoryIDDomainServiceMockRecorder
	isgomock struct{}
}

// MockIsExistByCategoryIDDomainServiceMockRecorder is the mock recorder for MockIsExistByCategoryIDDomainService.
type MockIsExistByCategoryIDDomainServiceMockRecorder struct {
	mock *MockIsExistByCategoryIDDomainService
}

// NewMockIsExistByCategoryIDDomainService creates a new mock instance.
func NewMockIsExistByCategoryIDDomainService(ctrl *gomock.Controller) *MockIsExistByCategoryIDDomainService {
	mock := &MockIsExistByCategoryIDDomainService{ctrl: ctrl}
	mock.recorder = &MockIsExistByCategoryIDDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsExistByCategoryIDDomainService) EXPECT() *MockIsExistByCategoryIDDomainServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockIsExistByCategoryIDDomainService) Exec(ctx context.Context, categoryID categorydm.CategoryID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, categoryID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIsExistByCategoryIDDomainServiceMockRecorder) Exec(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIsExistByCategoryIDDomainService)(nil).Exec), ctx, categoryID)
}
