// Code generated by MockGen. DO NOT EDIT.
// Source: contract_repository.go
//
// Generated by this command:
//
//	mockgen -source=contract_repository.go -destination=../../../support/mock/domain/contractdm/contract_repository_mock.go -package=contractdm_mock
//

// Package contractdm_mock is a generated GoMock package.
package contractdm_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	contractdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/contractdm"
	shared "github.com/TakayukiHirano117/architecture-study/src/core/domain/shared"
)

// MockContractRepository is a mock of ContractRepository interface.
type MockContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractRepositoryMockRecorder
	isgomock struct{}
}

// MockContractRepositoryMockRecorder is the mock recorder for MockContractRepository.
type MockContractRepositoryMockRecorder struct {
	mock *MockContractRepository
}

// NewMockContractRepository creates a new mock instance.
func NewMockContractRepository(ctrl *gomock.Controller) *MockContractRepository {
	mock := &MockContractRepository{ctrl: ctrl}
	mock.recorder = &MockContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractRepository) EXPECT() *MockContractRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockContractRepository) FindByID(ctx context.Context, planID shared.UUID) (*contractdm.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, planID)
	ret0, _ := ret[0].(*contractdm.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockContractRepositoryMockRecorder) FindByID(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContractRepository)(nil).FindByID), ctx, planID)
}

// FindContractByPlanIDAndUserID mocks base method.
func (m *MockContractRepository) FindContractByPlanIDAndUserID(ctx context.Context, planID, userID shared.UUID) (*contractdm.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContractByPlanIDAndUserID", ctx, planID, userID)
	ret0, _ := ret[0].(*contractdm.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindContractByPlanIDAndUserID indicates an expected call of FindContractByPlanIDAndUserID.
func (mr *MockContractRepositoryMockRecorder) FindContractByPlanIDAndUserID(ctx, planID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContractByPlanIDAndUserID", reflect.TypeOf((*MockContractRepository)(nil).FindContractByPlanIDAndUserID), ctx, planID, userID)
}

// Store mocks base method.
func (m *MockContractRepository) Store(ctx context.Context, contract *contractdm.Contract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockContractRepositoryMockRecorder) Store(ctx, contract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockContractRepository)(nil).Store), ctx, contract)
}
