// Code generated by MockGen. DO NOT EDIT.
// Source: mentor_recruitment_repository.go
//
// Generated by this command:
//
//	mockgen -source=mentor_recruitment_repository.go -destination=../../../support/mock/domain/mentor_recruitmentdm/mentor_recruitment_repository_mock.go -package=mentor_recruitmentdm_mock
//

// Package mentor_recruitmentdm_mock is a generated GoMock package.
package mentor_recruitmentdm_mock

import (
	context "context"
	reflect "reflect"

	mentor_recruitmentdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/mentor_recruitmentdm"
	gomock "go.uber.org/mock/gomock"
)

// MockMentorRecruitmentRepository is a mock of MentorRecruitmentRepository interface.
type MockMentorRecruitmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMentorRecruitmentRepositoryMockRecorder
	isgomock struct{}
}

// MockMentorRecruitmentRepositoryMockRecorder is the mock recorder for MockMentorRecruitmentRepository.
type MockMentorRecruitmentRepositoryMockRecorder struct {
	mock *MockMentorRecruitmentRepository
}

// NewMockMentorRecruitmentRepository creates a new mock instance.
func NewMockMentorRecruitmentRepository(ctrl *gomock.Controller) *MockMentorRecruitmentRepository {
	mock := &MockMentorRecruitmentRepository{ctrl: ctrl}
	mock.recorder = &MockMentorRecruitmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMentorRecruitmentRepository) EXPECT() *MockMentorRecruitmentRepositoryMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockMentorRecruitmentRepository) Store(ctx context.Context, mentorRecruitment *mentor_recruitmentdm.MentorRecruitment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, mentorRecruitment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockMentorRecruitmentRepositoryMockRecorder) Store(ctx, mentorRecruitment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMentorRecruitmentRepository)(nil).Store), ctx, mentorRecruitment)
}
