// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/app/planapp/get_plans_app_service.go
//
// Generated by this command:
//
//	mockgen -source=src/core/app/planapp/get_plans_app_service.go -destination=src/support/mock/app/planapp/get_plans_app_service_mock.go -package=planapp_mock
//

// Package planapp_mock is a generated GoMock package.
package planapp_mock

import (
	context "context"
	reflect "reflect"

	plandm "github.com/TakayukiHirano117/architecture-study/src/core/domain/plandm"
	gomock "go.uber.org/mock/gomock"
)

// MockGetPlansAppService is a mock of GetPlansAppService interface.
type MockGetPlansAppService struct {
	ctrl     *gomock.Controller
	recorder *MockGetPlansAppServiceMockRecorder
	isgomock struct{}
}

// MockGetPlansAppServiceMockRecorder is the mock recorder for MockGetPlansAppService.
type MockGetPlansAppServiceMockRecorder struct {
	mock *MockGetPlansAppService
}

// NewMockGetPlansAppService creates a new mock instance.
func NewMockGetPlansAppService(ctrl *gomock.Controller) *MockGetPlansAppService {
	mock := &MockGetPlansAppService{ctrl: ctrl}
	mock.recorder = &MockGetPlansAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPlansAppService) EXPECT() *MockGetPlansAppServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetPlansAppService) Exec(ctx context.Context) ([]*plandm.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx)
	ret0, _ := ret[0].([]*plandm.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetPlansAppServiceMockRecorder) Exec(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetPlansAppService)(nil).Exec), ctx)
}
