// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/app/planapp/plan_query_service.go
//
// Generated by this command:
//
//	mockgen -source=src/core/app/planapp/plan_query_service.go -destination=src/support/mock/app/planapp/plan_query_service_mock.go -package=planapp_mock
//

// Package planapp_mock is a generated GoMock package.
package planapp_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	plandm "github.com/TakayukiHirano117/architecture-study/src/core/domain/plandm"
)

// MockPlanQueryService is a mock of PlanQueryService interface.
type MockPlanQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanQueryServiceMockRecorder
	isgomock struct{}
}

// MockPlanQueryServiceMockRecorder is the mock recorder for MockPlanQueryService.
type MockPlanQueryServiceMockRecorder struct {
	mock *MockPlanQueryService
}

// NewMockPlanQueryService creates a new mock instance.
func NewMockPlanQueryService(ctrl *gomock.Controller) *MockPlanQueryService {
	mock := &MockPlanQueryService{ctrl: ctrl}
	mock.recorder = &MockPlanQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanQueryService) EXPECT() *MockPlanQueryServiceMockRecorder {
	return m.recorder
}

// GetPlans mocks base method.
func (m *MockPlanQueryService) GetPlans(ctx context.Context) ([]*plandm.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlans", ctx)
	ret0, _ := ret[0].([]*plandm.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlans indicates an expected call of GetPlans.
func (mr *MockPlanQueryServiceMockRecorder) GetPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlans", reflect.TypeOf((*MockPlanQueryService)(nil).GetPlans), ctx)
}
