// Code generated by MockGen. DO NOT EDIT.
// Source: src/core/domain/domain_service/tag.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tagdm "github.com/TakayukiHirano117/architecture-study/src/core/domain/tagdm"
	gomock "github.com/golang/mock/gomock"
)

// MockTagDomainService is a mock of TagDomainService interface.
type MockTagDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockTagDomainServiceMockRecorder
}

// MockTagDomainServiceMockRecorder is the mock recorder for MockTagDomainService.
type MockTagDomainServiceMockRecorder struct {
	mock *MockTagDomainService
}

// NewMockTagDomainService creates a new mock instance.
func NewMockTagDomainService(ctrl *gomock.Controller) *MockTagDomainService {
	mock := &MockTagDomainService{ctrl: ctrl}
	mock.recorder = &MockTagDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagDomainService) EXPECT() *MockTagDomainServiceMockRecorder {
	return m.recorder
}

// IsExistByTagId mocks base method.
func (m *MockTagDomainService) IsExistByTagId(ctx context.Context, tagId tagdm.TagId) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistByTagId", ctx, tagId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistByTagId indicates an expected call of IsExistByTagId.
func (mr *MockTagDomainServiceMockRecorder) IsExistByTagId(ctx, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistByTagId", reflect.TypeOf((*MockTagDomainService)(nil).IsExistByTagId), ctx, tagId)
}

// IsExistByTagName mocks base method.
func (m *MockTagDomainService) IsExistByTagName(ctx context.Context, tagName tagdm.TagName) (*tagdm.TagId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistByTagName", ctx, tagName)
	ret0, _ := ret[0].(*tagdm.TagId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistByTagName indicates an expected call of IsExistByTagName.
func (mr *MockTagDomainServiceMockRecorder) IsExistByTagName(ctx, tagName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistByTagName", reflect.TypeOf((*MockTagDomainService)(nil).IsExistByTagName), ctx, tagName)
}
